import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api } from "@/lib/api-client";
import { usePrimaryBusinessProfile } from "@/hooks/use-business-profile";
import type { BrandAsset, BrandAssetListResponse } from "@/lib/types";

function brandAssetsQueryKey(profileId: string | undefined) {
  return ["brand-assets", profileId];
}

/** The primary business's most recent brand kit, generated by the
 * /onboarding AI pipeline — undefined until onboarding has run once. */
export function usePrimaryBrandAsset() {
  const { profile, hasProfile, isLoading: profileLoading } = usePrimaryBusinessProfile();
  const query = useQuery({
    queryKey: brandAssetsQueryKey(profile?.id),
    queryFn: () =>
      api.get<BrandAssetListResponse>("/brand-assets", {
        business_profile_id: profile!.id,
        limit: 1,
      }),
    enabled: hasProfile && !!profile,
  });
  return {
    brandAsset: query.data?.items[0],
    isLoading: profileLoading || query.isLoading,
    isError: query.isError,
    profile,
  };
}

/** Patches the primary brand kit (e.g. an edited tagline or story) and
 * refreshes the cached brand-asset query. */
export function useUpdateBrandAsset(brandAssetId: string | undefined) {
  const queryClient = useQueryClient();
  const { profile } = usePrimaryBusinessProfile();
  return useMutation({
    mutationFn: (payload: Partial<BrandAsset>) =>
      api.patch<BrandAsset>(`/brand-assets/${brandAssetId}`, payload),
    onSuccess: () => {
      void queryClient.invalidateQueries({ queryKey: brandAssetsQueryKey(profile?.id) });
    },
  });
}

/** AI-recommends a logo (app.ai.image, kind="logo") from the brand's own
 * name/tagline/voice/palette and saves it as logo_url (POST
 * /brand-assets/{id}/generate-logo). Calling it again replaces the
 * previous recommendation — nothing keeps a history of past attempts. */
export function useGenerateLogo(brandAssetId: string | undefined) {
  const queryClient = useQueryClient();
  const { profile } = usePrimaryBusinessProfile();
  return useMutation({
    mutationFn: () => api.post<BrandAsset>(`/brand-assets/${brandAssetId}/generate-logo`),
    onSuccess: () => {
      void queryClient.invalidateQueries({ queryKey: brandAssetsQueryKey(profile?.id) });
    },
  });
}
