"""POST /websites/generate — Website Studio's "Generate" / "Regenerate"
action. Thin wrapper: calls app.ai.website.generator.generate_site() and
persists the result's metadata through the existing WebsiteService
(create on first generation, update — which auto-records a new version —
on regeneration). No new storage logic; the full generated page copy is
returned in the response since websites/website_versions has no column for
it (see the integration plan's schema notes) — the frontend re-fetches it
on each Website Studio visit rather than reading it back from storage.
"""

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession

from app.ai.providers import AIProviderResponseError
from app.ai.website.generator import generate_site
from app.api.deps import get_current_app_user, get_db_session
from app.models.enums import BrandAssetStatus
from app.models.user import User
from app.repositories.brand_asset import BrandAssetRepository
from app.repositories.business_profile import BusinessProfileRepository
from app.repositories.website import WebsiteRepository
from app.schemas.website import WebsiteCreate, WebsiteUpdate
from app.schemas.website_generation import (
    FAQItemOut,
    HeroOut,
    SectionOut,
    SiteProductOut,
    WebsiteGenerateRequest,
    WebsiteGenerateResponse,
)
from app.services.ai_mapping import to_ai_brand_kit, to_ai_business_profile
from app.services.website import WebsiteService

router = APIRouter()


@router.post(
    "/generate",
    response_model=WebsiteGenerateResponse,
    status_code=status.HTTP_200_OK,
    summary="Generate (or regenerate) a website from the business's brand kit",
    responses={
        404: {"description": "Business profile not found or not owned by the caller"},
        422: {"description": "No brand kit exists yet for this business — run onboarding first"},
        503: {"description": "AI provider unavailable"},
    },
)
async def generate_website(
    payload: WebsiteGenerateRequest,
    current_user: User = Depends(get_current_app_user),
    db: AsyncSession = Depends(get_db_session),
) -> WebsiteGenerateResponse:
    profiles = BusinessProfileRepository(db)
    profile = await profiles.get_by_id(payload.business_profile_id)
    if profile is None or profile.user_id != current_user.id:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Business profile not found.")

    brand_assets = BrandAssetRepository(db)
    brands, _ = await brand_assets.list_by_business_profile(
        profile.id, status=BrandAssetStatus.DRAFT, limit=1
    )
    if not brands:
        brands, _ = await brand_assets.list_by_business_profile(profile.id, limit=1)
    if not brands:
        raise HTTPException(
            status.HTTP_422_UNPROCESSABLE_ENTITY,
            "No brand kit exists for this business yet — complete onboarding first.",
        )
    brand = brands[0]

    try:
        spec = await generate_site(to_ai_business_profile(profile), to_ai_brand_kit(brand))
    except AIProviderResponseError as exc:
        raise HTTPException(status.HTTP_503_SERVICE_UNAVAILABLE, str(exc)) from exc

    website_service = WebsiteService(db)
    websites = WebsiteRepository(db)
    existing, _ = await websites.list_by_business_profile(profile.id, limit=1)

    if existing:
        website = await website_service.update(
            existing[0].id,
            WebsiteUpdate(
                website_name=profile.business_name,
                seo_title=spec.seo.title[:200],
                seo_description=spec.seo.description[:300],
                change_notes="Regenerated by Website AI",
            ),
        )
    else:
        website = await website_service.create(
            WebsiteCreate(
                business_profile_id=profile.id,
                website_name=profile.business_name,
                template="ai-generated",
                seo_title=spec.seo.title[:200],
                seo_description=spec.seo.description[:300],
            )
        )

    return WebsiteGenerateResponse(
        website=website,
        hero=HeroOut(
            headline=spec.pages.landing.hero.headline,
            subhead=spec.pages.landing.hero.subhead,
            cta=spec.pages.landing.hero.cta,
        ),
        sections=[
            SectionOut(type=s.type, heading=s.heading, body=s.body)
            for s in spec.pages.landing.sections
        ],
        about=spec.pages.about.body,
        products=[
            SiteProductOut(name=p.name, description=p.description, price=p.price)
            for p in spec.pages.products
        ],
        contact=spec.pages.contact.body,
        faq=[FAQItemOut(q=f.q, a=f.a) for f in spec.pages.faq],
        seo_keywords=spec.seo.keywords,
    )
