/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdvisorRouteImport } from './routes/advisor'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as BrandStudioRouteImport } from './routes/brand-studio'
import { Route as BusinessSetupRouteImport } from './routes/business-setup'
import { Route as CashflowRouteImport } from './routes/cashflow'
import { Route as ContentCalendarRouteImport } from './routes/content-calendar'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as MentorsRouteImport } from './routes/mentors'
import { Route as NoticedRouteImport } from './routes/noticed'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as SchemesRouteImport } from './routes/schemes'
import { Route as SocialStudioRouteImport } from './routes/social-studio'
import { Route as WebsiteStudioRouteImport } from './routes/website-studio'
import { Route as SiteSlugRouteImport } from './routes/site.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorRoute = AdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandStudioRoute = BrandStudioRouteImport.update({
  id: '/brand-studio',
  path: '/brand-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSetupRoute = BusinessSetupRouteImport.update({
  id: '/business-setup',
  path: '/business-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const CashflowRoute = CashflowRouteImport.update({
  id: '/cashflow',
  path: '/cashflow',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentCalendarRoute = ContentCalendarRouteImport.update({
  id: '/content-calendar',
  path: '/content-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorsRoute = MentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticedRoute = NoticedRouteImport.update({
  id: '/noticed',
  path: '/noticed',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesRoute = SchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialStudioRoute = SocialStudioRouteImport.update({
  id: '/social-studio',
  path: '/social-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteStudioRoute = WebsiteStudioRouteImport.update({
  id: '/website-studio',
  path: '/website-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteSlugRoute = SiteSlugRouteImport.update({
  id: '/site/$slug',
  path: '/site/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/analytics': typeof AnalyticsRoute
  '/brand-studio': typeof BrandStudioRoute
  '/business-setup': typeof BusinessSetupRoute
  '/cashflow': typeof CashflowRoute
  '/content-calendar': typeof ContentCalendarRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/memory': typeof MemoryRoute
  '/mentors': typeof MentorsRoute
  '/noticed': typeof NoticedRoute
  '/opportunities': typeof OpportunitiesRoute
  '/schemes': typeof SchemesRoute
  '/social-studio': typeof SocialStudioRoute
  '/website-studio': typeof WebsiteStudioRoute
  '/site/$slug': typeof SiteSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/analytics': typeof AnalyticsRoute
  '/brand-studio': typeof BrandStudioRoute
  '/business-setup': typeof BusinessSetupRoute
  '/cashflow': typeof CashflowRoute
  '/content-calendar': typeof ContentCalendarRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/memory': typeof MemoryRoute
  '/mentors': typeof MentorsRoute
  '/noticed': typeof NoticedRoute
  '/opportunities': typeof OpportunitiesRoute
  '/schemes': typeof SchemesRoute
  '/social-studio': typeof SocialStudioRoute
  '/website-studio': typeof WebsiteStudioRoute
  '/site/$slug': typeof SiteSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/analytics': typeof AnalyticsRoute
  '/brand-studio': typeof BrandStudioRoute
  '/business-setup': typeof BusinessSetupRoute
  '/cashflow': typeof CashflowRoute
  '/content-calendar': typeof ContentCalendarRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/memory': typeof MemoryRoute
  '/mentors': typeof MentorsRoute
  '/noticed': typeof NoticedRoute
  '/opportunities': typeof OpportunitiesRoute
  '/schemes': typeof SchemesRoute
  '/social-studio': typeof SocialStudioRoute
  '/website-studio': typeof WebsiteStudioRoute
  '/site/$slug': typeof SiteSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advisor'
    | '/analytics'
    | '/brand-studio'
    | '/business-setup'
    | '/cashflow'
    | '/content-calendar'
    | '/dashboard'
    | '/inventory'
    | '/login'
    | '/memory'
    | '/mentors'
    | '/noticed'
    | '/opportunities'
    | '/schemes'
    | '/social-studio'
    | '/website-studio'
    | '/site/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advisor'
    | '/analytics'
    | '/brand-studio'
    | '/business-setup'
    | '/cashflow'
    | '/content-calendar'
    | '/dashboard'
    | '/inventory'
    | '/login'
    | '/memory'
    | '/mentors'
    | '/noticed'
    | '/opportunities'
    | '/schemes'
    | '/social-studio'
    | '/website-studio'
    | '/site/$slug'
  id:
    | '__root__'
    | '/'
    | '/advisor'
    | '/analytics'
    | '/brand-studio'
    | '/business-setup'
    | '/cashflow'
    | '/content-calendar'
    | '/dashboard'
    | '/inventory'
    | '/login'
    | '/memory'
    | '/mentors'
    | '/noticed'
    | '/opportunities'
    | '/schemes'
    | '/social-studio'
    | '/website-studio'
    | '/site/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvisorRoute: typeof AdvisorRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BrandStudioRoute: typeof BrandStudioRoute
  BusinessSetupRoute: typeof BusinessSetupRoute
  CashflowRoute: typeof CashflowRoute
  ContentCalendarRoute: typeof ContentCalendarRoute
  DashboardRoute: typeof DashboardRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  MemoryRoute: typeof MemoryRoute
  MentorsRoute: typeof MentorsRoute
  NoticedRoute: typeof NoticedRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  SchemesRoute: typeof SchemesRoute
  SocialStudioRoute: typeof SocialStudioRoute
  WebsiteStudioRoute: typeof WebsiteStudioRoute
  SiteSlugRoute: typeof SiteSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor': {
      id: '/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-studio': {
      id: '/brand-studio'
      path: '/brand-studio'
      fullPath: '/brand-studio'
      preLoaderRoute: typeof BrandStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-setup': {
      id: '/business-setup'
      path: '/business-setup'
      fullPath: '/business-setup'
      preLoaderRoute: typeof BusinessSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashflow': {
      id: '/cashflow'
      path: '/cashflow'
      fullPath: '/cashflow'
      preLoaderRoute: typeof CashflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-calendar': {
      id: '/content-calendar'
      path: '/content-calendar'
      fullPath: '/content-calendar'
      preLoaderRoute: typeof ContentCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentors': {
      id: '/mentors'
      path: '/mentors'
      fullPath: '/mentors'
      preLoaderRoute: typeof MentorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticed': {
      id: '/noticed'
      path: '/noticed'
      fullPath: '/noticed'
      preLoaderRoute: typeof NoticedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes': {
      id: '/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof SchemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-studio': {
      id: '/social-studio'
      path: '/social-studio'
      fullPath: '/social-studio'
      preLoaderRoute: typeof SocialStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-studio': {
      id: '/website-studio'
      path: '/website-studio'
      fullPath: '/website-studio'
      preLoaderRoute: typeof WebsiteStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/$slug': {
      id: '/site/$slug'
      path: '/site/$slug'
      fullPath: '/site/$slug'
      preLoaderRoute: typeof SiteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvisorRoute: AdvisorRoute,
  AnalyticsRoute: AnalyticsRoute,
  BrandStudioRoute: BrandStudioRoute,
  BusinessSetupRoute: BusinessSetupRoute,
  CashflowRoute: CashflowRoute,
  ContentCalendarRoute: ContentCalendarRoute,
  DashboardRoute: DashboardRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  MemoryRoute: MemoryRoute,
  MentorsRoute: MentorsRoute,
  NoticedRoute: NoticedRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  SchemesRoute: SchemesRoute,
  SocialStudioRoute: SocialStudioRoute,
  WebsiteStudioRoute: WebsiteStudioRoute,
  SiteSlugRoute: SiteSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
